### PR TITLE
Niko/sequelize connection

### PR DESCRIPTION
**Pull request by niko79542**
+ re-seperate out schema.  Due to the cross-pollination between user/post/reply typedefs, I created two seperate folders for Types and Resolvers.  I installed merge-graphql-schemas to merge the types and resolvers seperately.  Then the types and resolvers are merged in src/controllers/graphql.  re: 56413842387e7f0b2a1ba56d5f5c8fa239c5fb72

+ Added associations between User and Post (todo: Reply). re: a10af1989240b92801ba6ff935a9c30c1e51e569

+ Redid Postservice module to have 2 public facing functions; resetRanking, and reSyncPosts.  You were right about the sequelize methods for create.  Took advantage of Model#createOrUpdate, which eliminated need for most of the previous PostService functions.  re: 4795a540b546c3a4c00618062ca60c771b8e8f37

### CODE REVIEW

**Comment by jay-ithiel** [comment]
I'm working through this PR. It's a huge PR so it will take a bit

Are these changes ready to be merged or do you have anything else you have to change?

For future pull requests, try to keep them small/concise as possible. The sequelize connection seems to be a large task so you can probably separate them into subtasks and make a PR for each subtask (You don't have to break this PR apart - it will take a lot more time to go through this branch and cherry pick commits). It will be easier to review, and if something breaks after merging, it will be easier to pinpoint the breaking point and to revert.

**Comment by niko79542** [comment]
Ok cool.  Yeah, these are ready to be merged.  Cool, yea i shoulda broken this one up.

**Comment by jay-ithiel** [comment]
You committed again?! aha no more changes to this branch please

**Comment by niko79542** [comment]
O.  Myb.  That was before the call yesterday

**Comment by jay-ithiel** [comment]
lgtm

**Comment by jay-ithiel** [comment]
The server isn't starting:

`npm start` fails with:

```
100x-Backend (niko/sequelize-connection)$ npm start

> 100x-backend@1.0.0 start /Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend
> nodemon

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/src/**/*
[nodemon] starting `kill-port --port 9229 && node --inspect -r ./src/server.js`
Process on port 9229 killed
Debugger listening on ws://127.0.0.1:9229/41f09c56-9941-4d70-b8b7-01529208d0b9
For help see https://nodejs.org/en/docs/inspector
server is listening to localhost http://localhost:4000/
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL , `name` VARCHAR(20) UNIQUE, `created_at` DATETIME, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
Executing (default): CREATE TABLE IF NOT EXISTS `posts` (`id` INTEGER NOT NULL , `permLink` VARCHAR(255) NOT NULL UNIQUE, `title` VARCHAR(48) NOT NULL, `body` TEXT NOT NULL, `createdAt` DATETIME, `netVotes` INTEGER UNSIGNED NOT NULL, `children` INTEGER UNSIGNED NOT NULL, `pendingPayoutValue` FLOAT NOT NULL, `trending` INTEGER DEFAULT 9999, `hot` INTEGER DEFAULT 9999, `postType` INTEGER NOT NULL, `tag1` VARCHAR(255) NOT NULL, `tag2` VARCHAR(255), `tag3` VARCHAR(255), `tag4` VARCHAR(255), `tag5` VARCHAR(255), `updatedAt` DATETIME NOT NULL, `userId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
Unhandled rejection SequelizeDatabaseError: Cannot add foreign key constraint
    at Query.formatError (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread [as _originalOnread] (net.js:598:20)
    at TCP.onread (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/async-listener/glue.js:188:31)
```

`npm run dev` fails with:

```
100x-Backend (niko/sequelize-connection)$ npm run dev

> 100x-backend@1.0.0 dev /Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend
> NODE_ENV=development nodemon ./src/server.js

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/src/**/*
[nodemon] starting `kill-port --port 9229 && node --inspect -r ./src/server.js ./src/server.js`
Process on port 9229 killed
Debugger listening on ws://127.0.0.1:9229/46d3b2b9-10b4-44e6-a933-554c4dcd5542
For help see https://nodejs.org/en/docs/inspector
server is listening to localhost http://localhost:4000/
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL , `name` VARCHAR(20) UNIQUE, `created_at` DATETIME, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
Executing (default): CREATE TABLE IF NOT EXISTS `posts` (`id` INTEGER NOT NULL , `permLink` VARCHAR(255) NOT NULL UNIQUE, `title` VARCHAR(48) NOT NULL, `body` TEXT NOT NULL, `createdAt` DATETIME, `netVotes` INTEGER UNSIGNED NOT NULL, `children` INTEGER UNSIGNED NOT NULL, `pendingPayoutValue` FLOAT NOT NULL, `trending` INTEGER DEFAULT 9999, `hot` INTEGER DEFAULT 9999, `postType` INTEGER NOT NULL, `tag1` VARCHAR(255) NOT NULL, `tag2` VARCHAR(255), `tag3` VARCHAR(255), `tag4` VARCHAR(255), `tag5` VARCHAR(255), `updatedAt` DATETIME NOT NULL, `userId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
Unhandled rejection SequelizeDatabaseError: Cannot add foreign key constraint
    at Query.formatError (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread [as _originalOnread] (net.js:598:20)
    at TCP.onread (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/async-listener/glue.js:188:31)
From previous event:
    at Query.run (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at retryParameters (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/sequelize.js:454:12)
    at QueryInterface.createTable (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/query-interface.js:279:29)
    at Promise.try.then.then (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/model.js:1128:39)
From previous event:
    at Function.sync (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/model.js:1128:8)
    at Promise.each.model (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/sequelize.js:719:50)
From previous event:
    at Promise.try.then.then (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/sequelize.js:719:22)
    at Immediate.<anonymous> (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/async-listener/glue.js:188:31)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Sequelize.sync (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/node_modules/sequelize/lib/sequelize.js:706:8)
    at Object.<anonymous> (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/src/controllers/graphql/connectors/connectors.js:6:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/src/controllers/graphql/connectors/index.js:1:80)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jayhwang/.sandbox/projects/todo/100x/100x-Backend/src/controllers/graphql/resolvers/user/userResolver.js:2:12)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
```

**Comment by jay-ithiel** [comment]
The code looked fine so I merged into master but when I tried to start the server, it failed. That's my bad I should have tried running your branch locally before merging into master.

I reverted the merge into master so just make a new PR after the fix

**Pull request merged**
