### PR TITLE
change rds names

### PR DESCRIPTION
**Pull request by jay-ithiel**

### CODE REVIEW

**Comment by niko79542** [comment]
Sounds good.  Ill make sure this runs on aws and check it in

**Comment by jay-ithiel** [comment]
Does it work on rds still? Please merge if it does 🙏

**Comment by niko79542** [comment]
Sure.  Let me take a look

**Comment by niko79542** [comment]
Doesn't seem like we can change the default env variables on aws.  Closing
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.db.html

**Pull request closed without merging**
